### ISSUE TITLE
Question on Footnotes and Cross Refs

### ISSUE THREAD

**Issue by joelthe1** [ubsicap/usfm#101]
@klassenjm could you kindly provide guidance on these questions relating mainly to footnotes and cross references in the USFM spec?

I am asking these on behalf of @kavitharaju

**1. use of +xt**
 we have seen instances of `\xt` used outside of cross-references like this. And we have permitted such usage in [usfm-grammar](https://github.com/Bridgeconn/usfm-grammar).
```
\c 2
\cd \xt 1|GEN 2:1, x-text="value"\xt* Бог благословляет седьмой день; \xt 8|GEN 2:8\x* человек в раю Едемском;
четыре реки; дерево познания добра и зла. \xt 18|GEN 2:18\x* Человек дает названия животным.
\xt 21|GEN 2:21\xt* Создание женщины.
\p
\v 1 Так совершены небо и земля и все воинство их.
\p
```
Is it valid to use `\xt` outside like this?

We encountered another usage of the same marker, as shown below, where it is used like a nested character marker, inside a footnote.
```
\q1
\v 2 но в Законе Вечного\f + \fr 1:2 \fk Вечный \ft – на языке оригинала: «Яхве». Под этим именем Всевышний открылся Мусе и народу Исраила (см. \+xt Исх. 3:13-15\+xt*). См. пояснительный словарь.\f* находит радость
\q2 и о Законе Его размышляет день и ночь.
```
 Is it valid to use `\xt` like a nested character marker? Is it valid to have markers other than footnote content markers, within footnotes(and cross-refs)? We are allowing it in extended footnotes(`\ef`) as that is explicitly mentioned in the spec, but not in normal footnotes.

**2. Closing of internal markers of footnotes and cross-refs**
 we have seen footnote content element `\fqa` having a closing(`\fqa*`) even though it is not specified so in the spec. Similarly `\xq`, in cross-references also has a closing in some of the examples we saw. So is it valid to say that all content markers of footnotes and cross refernces may have an optional corresponding closing marker?

**3. `\ft` outside footnote**
 This is a snippet taken from one of the examples listed in the [USFM spec](https://ubsicap.github.io/usfm/notes_study/intros_div.html#division-and-section-introductions):
```
\ip Jesus returns to Galilee and does not go back to Judea until the close of his public
ministry. There is no indication of how long his Galilean ministry lasted: only when he is
back in Judea is a \w festival \ft (\w passover\ft ) mentioned (14.1). He spends...
```
here the usage of `\w` and `\ft` seem peculiar in that they are not closed and seem to be nested in a peculiar way. Is this a valid usage or a typo? And can we use `\ft` outside footnote at all?

**4. `\fig` syntax**
This is another snippet from the [USFM spec](https://ubsicap.github.io/usfm/notes_study/sidebars.html#esbe):
```
\fig Christian Fish Image|christfish.jpg||||Ihsous Christos Theou
Uios Swthr|\fig*
```
We have seen `\fig` marker used like this with several pipes( `|` ) in other files we have worked with also. But we haven't accommodated this syntax in grammar as the spec doesn't mention the usage of attributes like this. Is this valid USFM 3?

**Comment by klassenjm** [comment]
Hi @joelthe1 and @kavitharaju,

I'm sorry to have kept you waiting for a reply.

**Re: 1 - use of +xt**
Yes - in USFM you can use `\xt ...\xt*` widely for target scripture references. This is distinct from other \x... markers which are used within `\x ...\x*`. The documentation is not clear on this, I can see. The reference stylesheet for Paratext has a long list of markers which `\xt` can occur under: 

```
\OccursUnder ip im ipi imi ipq imq ipr iq iq1 iq2 iq3 io io1 io2 io3 io4 
ms ms1 ms2 s s1 s2 s3 s4 cd sp d lh li li1 li2 li3 li4 lf lim lim1 lim2 lim3 lim4 
m mi nb p pc ph phi pi pi1 pi2 pi3 pr pmo pm pmc pmr po q q1 q2 q3 q4 
qc qr qd qm qm1 qm2 qm3 tr th1 th2 th3 th4 thr1 thr2 thr3 thr4 
tc1 tc2 tc3 tc4 tcr1 tcr2 tcr3 tcr4 f fe x ef ex
```

In USFM syntax, anytime a character level marker is nested within another character level marker, it should have the `+` syntax applied. So, yes, the `\+xt Исх. 3:13-15\+xt*` with `ft` is good.

**Re: 2. Closing of internal markers of footnotes and cross-refs**
This section would be a reference on this:
https://ubsicap.github.io/usfm/about/syntax.html#endmarkers-in-footnotes-and-cross-references

The practice of not explicitly closing character level markup within notes and xrefs became very common years ago. It helped reduce the amount of markup in the text and made it easier to handle (especially before any formatted editor). As you'll see in the note above, either

```
\f + \fk Issac: \ft In Hebrew means "laughter"\f*
```
or
```
\f + \fk Issac:\fk* \ft In Hebrew means "laughter"\ft*\f*
```
is acceptable syntax.

Nested markup should always have explicit opening and closing.

**Re: 3. \ft outside footnote**
Thank you for sharing this! It is entirely an error in the documentation, which will get fixed.

**Re: 4. \fig syntax**
This example you located in the documentation is also wrong. This is a remnant of [USFM 2 syntax](https://ubsicap.github.io/usfm/v2.5/characters/index.html#fig-fig) and also needs to be fixed. Thank you also for reporting this. That figure syntax should be:
```
\fig Ihsous Christos Theou Uios Swthr|alt="Christian Fish Image" src="christfish.jpg" size="col" ref="1.18"\fig*
```

**Comment by joelthe1** [comment]
Thanks for taking the time to answer @klassenjm! This issue has been addressed fully; closing for now.
