### ISSUE TITLE
Improve \toc3 example

### ISSUE THREAD

**Issue by RobH123** [ubsicap/usfm#102]
As I understand it (and I could be quite wrong), the \toc3 field is intended to contain the local language abbreviation of the bookname as would be used in \r section references and \x cross-references. It might reasonably be in the range of 2-6 characters long.

If that's correct, the "Mat" example in http://ubsicap.github.io/usfm/master/identification/index.html is a bit misleading/ambiguous, because other than case, it also matches the MAT bookcode. Perhaps an example that showed a different abbreviation would help clarify, esp. a non-3-letter one like "Jd" or "3Jhn" or a non-English example.

**Comment by klassenjm** [comment]
Hi @RobH123: `Mat` is the abbreviation used in some English GNT texts, so I'm not sure how it is ambiguous. There are various cases where the 3 letter book code in `\id` is the same as the English `\toc3` abbreviation. As you suggested though, I've added an additional language example (Spanish). The docs will be updated shortly.
https://ubsicap.github.io/usfm/identification/index.html#toc
