### ISSUE TITLE
Cross reference example

### ISSUE THREAD

**Issue by cmahte** [ubsicap/usfm#103]
The example in the expanded use of \xt  showing it's use in a chapter index is confusing or displays incorrect usage? 

The first use \xt ... \xt* is as expected, but the second and 3rd example terminate with a \x* not a \xt*.  Is this allowed? If it is allowed, some text somewhere describing that character fields actually terminate with at the next slash .... 

_____

Text Sample - Genesis 2 (Russian Synodal, Protestant Version, extending the sample for \cd - chapter description)

\c 2
\cd \xt 1|GEN 2:1\xt* Бог благословляет седьмой день; \xt 8|GEN 2:8\x* человек в раю Едемском;
четыре реки; дерево познания добра и зла. \xt 18|GEN 2:18\x* Человек дает названия животным.
\xt 21|GEN 2:21\xt* Создание женщины.
\p

**Comment by klassenjm** [comment]
Thank you for catching this error in the documentation Michael. The examples should be:

```
\c 2
\cd \xt 1|GEN 2:1\xt* Бог благословляет седьмой день; \xt 8|GEN 2:8\xt* человек в раю Едемском;
четыре реки; дерево познания добра и зла. \xt 18|GEN 2:18\xt* Человек дает названия животным.
\xt 21|GEN 2:21\xt* Создание женщины.
\p
```

The correction will appear shortly.
