### ISSUE TITLE
picture set bottom-left pushes text to right hand column, set top-right it vanishes.

### ISSUE THREAD

**Issue by davidg-sil** [ubsicap/usfm#107]
(at least on a small page). I'm guessing that moving to the right is a balancing issue. 
The vanishing image may be related, not sure which most serious.

[test.pdf](https://github.com/ubsicap/usfm/files/4886504/test.pdf)

test.tex:
```
\input "paratext2.tex"
\stylesheet{usfm.sty}
\BodyColumns=2
%\input "usfmTex-ext.tex"
%\input "hooks.tex"
\tracing{g}
% Set added material in desired form
\csname ColorFontstrue\endcsname
\ptxfile{test.usfm}
\bye
```

test.usfm:
```
\s This is a title
\p
\v 1 This is normal text. 
\fig This is a rose, not a fig |loc="bl" src="image.jpg" alt="Figs are tasty"  ref="1:1" size="col*0.5"\fig*
\v 2 I wonder what happens here.
```
(get rid of the *0.5 if using historic macro versions)

**Comment by klassenjm** [comment]
@davidg-sil Did this issue belong at [ptx2pdf](https://github.com/sillsdev/ptx2pdf)?

**Comment by davidg-sil** [comment]
Yes, sorry!  Typed into the wrong tab
