### ISSUE TITLE
usfm_sb.sty calls esb a paragraph style

### ISSUE THREAD

**Issue by davidg-sil** [ubsicap/usfm#108]
It seems incorrect to me that ```usfm_sb.sty``` classifies `\esb` ... `\esbe` as ```\StyleType Paragraph``
It would seem more reasonable to classify as something else. It is not cancelled by other paragraph types, 
and by itself provides no styling. Can i suggest a new classification, e.g.
```
\StyleType ParagraphGroup
``` 
or 
```
\StyleType SideBar
```

**Comment by klassenjm** [comment]
@davidg-sil  - your observation is quite correct.

This is something which needs to be forwarded to the Paratext development team. The stylesheets are a Paratext expression of USFM. Practically, they are defacto a reference for some USFM properties. I will submit this as something for consideration on their end.
