### ISSUE TITLE
`fv` marker uses the "Use" description from `fp`

### ISSUE THREAD

**Issue by Rolf-Smit** [ubsicap/usfm#111]
While looking at the documentation for the `fv` marker:
https://ubsicap.github.io/usfm/master/notes_basic/fnotes.html#fv-fv

I found that it seems to be reusing the same "Use" as the `fp` marker:

> Use this marker to if you need to indicate the start of a new paragraph within a footnote (uncommon).

Which seems to be wrong, I would expect it to say something like:

> Use this marker if you need to render a verse number within a footnote (uncommon).

**Comment by klassenjm** [comment]
@Rolf-Smit Thank you for catching this error and sending a helpful note. I have updated the text to match the USX description for style [fv](https://ubsicap.github.io/usx/notes.html#fv).

**Comment by klassenjm** [comment]
Incorrectly referenced this issue in a9ba3ca. The commit should have referenced #114
