### ISSUE TITLE
\jmp \Attributes

### ISSUE THREAD

**Issue by AndyWarren-Rothlin** [ubsicap/usfm#113]
We have been unable to use this feature of USFM3:
https://ubsicap.github.io/usfm/linking/index.html
as reported here:
https://support.paratext.org/t/invalid-reference-errors-with-link-anchors-and-named-targets/4041 

The latest usfm.sty includes the line:
#!\Attributes link-href
Should this in fact read as follows?
#!\Attributes link-href link-title link-id

(Posting at the recommendation of Tim Steenwyk. Also discussed with Elbert Boot.)

**Comment by klassenjm** [comment]
@AndyWarren-Rothlin 

It is helpful that this specific issue has been reported to the PT developers.

In Paratext 9, there was a level of support added for USFM 3 markup options. For example: support for the new attribute syntax in general, and as implemented with `\w ...|...\w*` and the updated `\fig ...|...\fig*. I believe much work was done on checking tools to properly check markup, even if PT did not enable new user functionality from the markup. But full support in Paratext for some things - such as full support for linking options - was not completed yet. I'm not aware that named anchors or links to anchors would operate in Paratext yet. As resources are given to further development of study Bible support, I'm optimistic that more will be addressed.

If `usfm.sty` file needs to be updated in ways to enable Paratext, they could commit a pull request to the usfm.sty file here.
