### ISSUE TITLE
White space after verse number/range

### ISSUE THREAD

**Issue by davidg-sil** [ubsicap/usfm#115]
**Summary:** "Everyone" assumes there should be a space between a verse number/range and whatever comes next. Please can this be in the specification.

**Longer version**
Although every markup example I've seen puts a space after a verse number or verse range, and Paratext inserts this space, I can't see anything in the specification that actually specifies it should be there. I assume that this is an omission rather than intentional, can it please be explicitly added that there should be white-space after verse and chapter numbers?

I know that it's the role of processors to follow the specification not vice-versa, but the space seems to be well established and the ptx2pdf XeTeX macros rely on that whitespace being there as the delimiter to mark the end of the number or range.
i.e. verse 2 below will crash the ptx2pdf macros because of the lack of space.
```
\v 1 \x - \xt Gen 1:1\x* Verse text without any problems
\v 2\x - \xt Rev 20:14\x* Parsing error
```
**Suggested revision**
```
:Syntax: ``\v_#_``
:Type: character
:Added: 1.0
:Use: Verse number. |br|
	Marker is followed by the verse number #, a space or new-line (to mark the end of the number), and the text of the verse.
```

**Comment by klassenjm** [comment]
Hi @davidg-sil - I updated the docs with this recommendation. I did not include the 'or new-line' text, since I think it would be good to emphasize this one practice, and keeping `_` clear as a space.
