### ISSUE TITLE
Extend USFM marker \mi to \mi#

### ISSUE THREAD

**Issue by rfpng** [ubsicap/usfm#131]
In August 2018 I made a proposal to the Paratext support group to extend the USFM marker \mi to \mi#. Apparently this is now recorded as PTXS-16994 (The original confirmation I received had the number PTXS-17401).

Unfortunately I never heard if my proposal was considered. The issue is still important to me:
In an NT I typeset, \mi1 and \mi2 was used in the glossary. This worked very well but in electronic publishing this causes problems because the process doesn't know about \mi#.

Here is the structure of a glossary entry:
\li1 - Main Entry Headline
\pi1 - Main Entry Description
\mi1 - Indented non-first-line-indented paragraph

The above works fine, but some of the entries also have sub-entries as follows:
\li2 - Sub Entry Headline
\pi2 - Sub Entry Description
\mi2 - Further indented non-first-line-indented paragraph ← Doesn't exist, and that's the problem!

Many paragraph markers have numbered counterparts, but \mi doesn't. It would be very helpful to me if it did!

Thank you very much for considering this. 

PS: I'll gladly send you more information about this if needed.

**Comment by rfpng** [comment]
It's now over 5 years since I first proposed extending the USFM marker \mi to \mi#. Any chance for that?
It's definitely still an issue to me!

PS: The original number was Case 39697. Later it became PTXS-17401, then PTXS-29997. (Note: The address in my first email to Paratext Support is no longer valid.)

**Comment by rfpng** [comment]
I just looked at this issue again and realized that I had actually reported this as a problem already in February 2015! (Over 9 years ago.)
It's still an issue. 
I can't electronically publish our glossary in a decent looking format without \mi#.
Thanks for considering this.

**Comment by klassenjm** [comment]
Dear @rfpng 
I have a made a clone of this issue in the current USFM and USFX working group repository. 
https://github.com/usfm-bible/tcdocs/issues/75

I'm sorry you have not received the feedback you have requested.

I don't know what digital tools you are working -- but (for now) if those tools support working with user-generated (non-USFM) markup, you could define and add your own markup such as \zmi#

**Comment by klassenjm** [comment]
This issue is moved to the usfm-bible/tcdocs repo.
