### ISSUE TITLE
List item total (add \litl ...\litl*)

### ISSUE THREAD

**Issue by klassenjm** [ubsicap/usfm#14]
## Proposal

* Add character marker pair `\litl …\litl*` for “list item total”.

A companion USX 3.0 proposal exists at: ubsicap/usx#12

#### Details

In various locations (e.g. Joshua 12, 1 Chronicles 25, Ezra 2, Nehemiah 7) the scripture text contains types of “accounting” lists, where numeric totals would ideally be presented right-aligned (or left-aligned in right-to-left texts). Markup for denoting the _total_ component of the text within a list item (\li) would provide a flexible alternative to using tables for the same content.

**Note:** There is some overlap in purpose with the proposal for #13 (structured list items).

## Example

Nehemiah 7:8-10

```text
\p The list of the men of Israel:
\li1 \v 8 the descendants of Parosh \litl 2,172\litl*
\li1 \v 9 of Shephatiah \litl 372\litl*
\li1 \v 10 of Arah \litl 652\litl*
```

**Comment by DavidHaslam** [comment]
NB. (FIO) Not to be confused with **\lit text** Liturgical note/comment.

See [\lit](https://ubsicap.github.io/usfm/characters/index.html#lit)
