### ISSUE TITLE
Improve search to include *all* markers?

### ISSUE THREAD

**Issue by davidg-sil** [ubsicap/usfm#146]
The web-pages (search engine) currently seem to do a good job if you're looking for a topic. But if you're looking  to see what the spec says for, e.g. `\k`, or what `\ip` is supposed to mean, you're down to guessing or reading all of the documentation.  There are clearly index entries for *some* of the markers, but it's by no means all.

**Comment by klassenjm** [comment]
Hi David,

The search utility provided via the sphinx document builder and the RTD ('read the docs') theme has proved to be awkward and inflexible.

The problem with search is being solved in the updated documentation for USFM and USX (together) at [https://docs.usfm.bible](https://docs.usfm.bible). Try entering a marker in the search box at the top of that site. This will become the reference docs a bit later this year.
