### ISSUE TITLE
USFM documentation error \v being a paragraph marker instead of character marker

### ISSUE THREAD

**Issue by lightroomstatistics** [ubsicap/usfm#150]
The documentation says that \v is  of type character, see [\v](http://ubsicap.github.io/usfm/chapters_verses/index.html#v).

I.m.h.o. \v is of type paragraph, because it has no end tag.

**Comment by klassenjm** [comment]
It's true that the both `\c` and `\v` markers do not have closing markers. It is necessary to understand them as neither truly a paragraph or  a character, but rather like a milestone in the text. They are like a character marker in the sense that they have content to publish (the chapter or verse number) and they are also not strictly following the syntax of USFM 3 milestones. `\c` and `\v` are unique (and, they've followed this syntax for decades). An upcoming revision to the [USFM and USX documentation](https://docs.usfm.bible/usfm-usx-docs/latest/cv/index.html) offers some additional text about the milestone-like nature of chapter and verse markers.
