### ISSUE TITLE
Syntax for milestones

### ISSUE THREAD

**Issue by klassenjm** [ubsicap/usfm#33]
## Proposal
- Specify a general purpose syntax for indicating the start and ending milestones for a span of text, where the boundaries of the content being marked may cross one or more paragraph boundaries.
#### Background

A milestone type markup is required when a document has two or more structures that interact in a non-hierarchical manner. This is also referred to as _overlapping_ or _concurrent_ markup. The principle example of this type of overlapping structure in scripture text is the contrast between 1) the paragraph structures used to express the discourse / narrative of the text and 2) the division of the text into books, chapters and verses.

Another example of an overlapping structure is when there is a need to indicate the start and end of the quotations of the actors who are speaking within the text. These spans of text will commonly cross paragraph boundaries. (See: `\qt-s\* ... \qt-e\*` - Milestone for quotations / speaker (add \qt-s* and \qt-e*) - USFM 3.0 #35)

A companion USX 3.0 proposal exists at: ubsicap/usx#26
#### General Syntax

Milestones follow a syntax similar to the current character level markup. The significant distinguishing feature is that milestones introduce a new self-closing syntax. This self-closing syntax is the feature which identifies the marker as a milestone. The milestone will mark the _position_ of the start _or_ end of a span of text, but it does not strictly _contain_ the text, as with a regular character level markup.

A benefit of the self-closing marker syntax is that it also results in a shorter markup text.

Self closing markup is indicated by immediately terminating the marker and any attributes with a backslash and asterisk. The following markup is the basic form proposed for marking the start of a quotation / speaker milestone.

``` text
\qt-s\*
```

The corresponding markup for the end milestone would be:

``` text
\qt-e\*
```

For comparison and contrast, the existing basic character level USFM markup for marking [quoted text](http://ubsicap.github.io/usfm/characters/index.html#qt-qt) (typically OT quotations in the NT) follows the syntax.

``` text
\q1 Text \qt quoted text\qt*
\q2 \qt quoted text\qt*
```
#### Indicating Start and End Milestones

A milestone marker must always end with either `-s` or `-e`
- `-s` indicates that the milestone is for marking the **start** of a span of text.
- `-e` indicates that the marker is an **end** milestone. 

#### Standalone Milestones

Milestones do not need to occur in pairs or require the use of start `-s` and end `-e` marker suffixes. The syntax can also be used for a standalone milestone.

**Example:** (note use of the `\z`  namespace in this example)

```
    \zms\*
```

USFM does not formally provide any standalone milestones. This may change with future updates to USFM 3.x, as use of milestones highlights specific needs. 

#### Attributes

Following the syntax for assigning word-level descriptive attributes (USFM 3.0 #24), the following optional attributes can be added to any USFM milestone marker.
- **id** - a unique identifier which can be used to unambiguously associate the start and ending milestone marker.
  - The id can be composed of any mixture of numbers, letters, and underscores, and should be unique throughout the scripture text for the selected milestone type.

``` text
\qt-s |id="qt123" who="Pilate"\*“Are you the king of the Jews?”\qt-e |id="qt123"\*
```

Additional attributes may be required by a specific USFM milestone marker (e.g the use of the `who` attribute in the above quotation example).
#### Levels

As with other USFM [numbered markers](http://ubsicap.github.io/usfm/about/syntax.html#numbered-markers), a numeric variable may be added to a milestone marker to indicate a relative weighting or level. In the example of the quotation / speaker milestone, a numbered version of the marker may be used to indicate the level of nesting of the quotation being marked (i.e. a quote within a quote).

``` text
\p
\v 22 Paul stood up in front of the city council and said, \qt1-s |who="Paul"\*“I see that in 
every way you Athenians are very religious.
\v 23 For as I walked through your city ...
...
Yet God is actually not far from any one of us;
\v 28 as someone has said,
\q1 \qt2-s |who="someone"\*‘In him we live and move and exist.’\qt2-e\*
\b 
\m It is as some of your poets have said,
\q1 \qt2-s |who="some poets"\*‘We too are his children.’\qt2-e\*
...
\v 31 For he has fixed a day in which he will judge the whole world with justice by means 
of a man he has chosen. He has given proof of this to everyone by raising that man from 
death!”\qt1-e\*
```

The unnumbered version may be used when only one level of marker exists within the project text. Numbers should always be included when more than one level of the marker exists within the project text.
## 3.0 Milestone Markers
- `\qt-s\* ...\qt-e\*` - Milestone for quotations / speaker (add \qt-s* and \qt-e*) - USFM 3.0 #35

**Comment by jag3773** [comment]
I'm trying to think through the possibility of using this feature to denote syntax within USFM.  For instance, could this be used to mark the function that each part of a sentence plays (e.g. subject, verb, object, etc.)?  If so, I don't see where the "generic" markup for this would be.  The example above only shows `\qt-s\* ...\qt-e\*`, which I think is reserved specifically for marking quotations (#35).

Am I misunderstanding, or is there a generic milestone syntax that is available for use?

**Comment by klassenjm** [comment]
Update documentation to express

- optional start and end suffix on milestone markers
- use of `\z` namespace to for user created extentions.

Confirm that these meet needs in #58 and #59

**Comment by klassenjm** [comment]
Use start (sid) and end (eid) attributes for milestone pairs (also commented in #35)
