### ISSUE TITLE
Milestones for quotations / speaker (add \qt#-s\* and \qt#-e\*)

### ISSUE THREAD

**Issue by klassenjm** [ubsicap/usfm#35]
## Proposal
- Following the syntax for milestones (USFM 3.0 #33), add milestones `\qt#-s` and `\qt#-e` for marking the start and end of quotations, typically used for indicating the speaker of the text.
  - The variable `#` represents the level of nesting of the quotation being marked (i.e. a quote within a quote).

A companion USX 3.0 proposal exists at: ubsicap/usx#27
#### Attributes

The following optional attributes can be added to any USFM milestone marker.

- **sid** - a unique identifier which can be used to unambiguously identify the starting milestone, and to clearly associate the starting milestone with the ending milestone (eid).
  - The id can be composed of any mixture of numbers, letters, and underscores, and should be a unique ``sid`` throughout the scripture text.
- **eid** - a unique identifier which can be used to unambiguously identify the ending milestone, and to clearly associate the ending milestone with the starting milestone (sid).
  - If the `sid` attribute is used for the starting milestone in a milestone pair, the ending milestone must include `eid`

``` text
\qt-s |sid="qt_123"\*“Are you the king of the Jews?”\qt-e |eid="qt_123"\*
```

Following the syntax for assigning word-level descriptive attributes (USFM 3.0 #24), explicitly extend milestone marker `\qt#s ...* with the following attributes:
- **who** - indicates the speaker of the quotation.

``` text
\qt-s |sid="qt_123" who="Pilate"\*“Are you the king of the Jews?”\qt-e |eid="qt_123"\*
```
## Examples
- **Matthew 27:11-14 (GNT)** - Start and end quotation milestones with `who` attribute; without levels.

``` text
\v 11 Jesus stood before the Roman governor, who questioned him. \qt-s |who="Pilate"\*“Are you 
the king of the Jews?”\qte\* he asked.
\p \qt-s |who="Jesus"\*“So you say,”\qte\* answered Jesus.
\v 12 But he said nothing in response to the accusations of the chief priests and elders.
\p
\v 13 So Pilate said to him, \qt-s |who="Pilate"\*“Don't you hear all these things they accuse 
you of?”\qt-e\*
\p
\v 14 But Jesus refused to answer a single word, with the result that the Governor was greatly 
surprised.
```
- **Acts 17:22-31** - Start and end quotation milestones with `who`, `level`, and `id` attributes.
  - The `id` in this example has been formed using a combination of the milestone type and start milestone reference.

``` text
\p
\v 22 Paul stood up in front of the city council and said, \qt1-s |sid="qt_ACT17:22" who="Paul"\*
“I see that in every way you Athenians are very religious.
\v 23 For as I walked through your city and looked at the places where you worship, I found an 
altar on which is written, ‘To an Unknown God.’ That which you worship, then, even though you 
do not know it, is what I now proclaim to you.
\v 24 God, who made the world and everything in it, is Lord of heaven and earth and does not 
live in temples made by human hands.
\v 25 Nor does he need anything that we can supply by working for him, since it is he himself 
who gives life and breath and everything else to everyone
\v 26 From one human being he created all races of people and made them live throughout the 
whole earth. He himself fixed beforehand the exact times and the limits of the places where they 
would live.
\v 27 He did this so that they would look for him, and perhaps find him as they felt around for 
him. Yet God is actually not far from any one of us;
\v 28 as someone has said,
\q1 \qt2-s |who="someone"\*‘In him we live and move and exist.’\qt2-e\*
\b 
\m It is as some of your poets have said,
\q1 \qt2-s |who="some poets"\*‘We too are his children.’\qt2-e\*
\b 
\m
\v 29 Since we are God's children, we should not suppose that his nature is anything like an 
image of gold or silver or stone, shaped by human art and skill.
\v 30 God has overlooked the times when people did not know him, but now he commands all 
of them everywhere to turn away from their evil ways.
\v 31 For he has fixed a day in which he will judge the whole world with justice by means of a 
man he has chosen. He has given proof of this to everyone by raising that man from death!”
\qt1-e |eid="qt_ACT17:22"\*
```

**Comment by jag3773** [comment]
We've had a particular need for this in Song of Songs.

**Comment by klassenjm** [comment]
Use start (sid) and end (eid) attributes for milestone pairs.

**Comment by schierlm** [comment]
Are you aware of any (freely licensed) Bible texts in either USFM or USX format that include speaker information (other than `\wj`?). I like to add speaker support to my converter software and could use some real-world test files for this.
