### ISSUE TITLE
Sample and rendering don't match for \tcr#

### ISSUE THREAD

**Issue by DavidHaslam** [ubsicap/usfm#40]
[Documentation for Tables \tcr#](https://ubsicap.github.io/usfm/tables/index.html#usfmc-table-colspan)

See [screenshot](https://www.dropbox.com/s/an0g5tjk1itb5qw/Screenshot%202016-12-31%2019.44.26.png?dl=0).

**Text and Formatting Sample** - Numbers 2.10-16 (GNT)

**Error:** The rendered example below that is actually for Numbers 2.3-9

**Comment by DavidHaslam** [comment]
Just observed a similar mismatch in the examples for [**\mt#**](https://ubsicap.github.io/usfm/titles_headings/index.html#mt)

The second example is for **Introduction to John (GNT)**.
**Error:** The rendered example below that is just a further copy of that for the **Introduction to Acts (GNT)**.

**Comment by klassenjm** [comment]
Thanks, @DavidHaslam
