### ISSUE TITLE
The need for a general purpose milestone tag in USFM

### ISSUE THREAD

**Issue by DavidHaslam** [ubsicap/usfm#58]
### Proposal for extending USFM

In **OSIS 2.1.1** there is a **general purpose milestone** element that takes the form

`<milestone type="x-whatever" />`.

_Further attributes are allowed._

It would be very useful to have something equivalent in **USFM 3.x** that could be readily converted to that OSIS element.

I therefore propose the marker **\mg** for this purpose.

#### Example use:

Suppose it's one of the modern translations that [omits various verses](https://en.wikipedia.org/wiki/List_of_Bible_verses_not_included_in_modern_translations).

An omitted verse such as any of **Mark 9:44,46,48** could be marked with just this milestone.
```
\v 44 \mg |type="x-omitted"\*
```
There's no verse text, but having a milestone in the OSIS will ensure that various Bible study programs would not meet an inability to **navigate past** this verse when using (e.g.) a **spinner control** in the GUI.

Unlike existing milestones syntax, the general one would not require the `-s` and `-e` start and end suffices.

I'm sure that further uses will arise in USFM, as we've often seen several other uses of such a milestone in various OSIS Bible text files.

**Comment by klassenjm** [comment]
Addressed by updates / clarification in #33 concerning standalone milestones.
