### ISSUE TITLE
What is the USFM equivalent to the OSIS colophon type of div element?

### ISSUE THREAD

**Issue by DavidHaslam** [ubsicap/usfm#69]
OSIS 2.1.1 defines a **colophon** as a **type** attribute value for the **div** element.

> Most often found in hand written texts to identify the author, place of composition but does
> occur in some printed works.

It's commonly used for the attribution sentences found at the end of the 14 Pauline Epistles (if we also count Hebrews)

e.g. After Romans 16 in the KJV, we read:

> Written to the Romans from Corinthus, and sent by Phebe servant of the church at Cenchrea. 

Although USFM defines a **closer** tag **\cls_text...** ,  none of the examples use it for this purpose.

What is the correct USFM tag to use for such colophons?

**Comment by klassenjm** [comment]
@DavidHaslam There is not an exact equivalent. The KJV54 (BFBS) uses \iex (explanatory or bridge text)

```
\v 27 to God only wise, \add be\add* glory through Jesus Christ for ever. Amen.
\iex Written to the Romans from Corinthus, and sent by Phebe servant of the church at 
Cenchrea. 
```
