### ISSUE TITLE
Milestones for translator's section / chunk (add \ts-s\* and \ts-e\*)

### ISSUE THREAD

**Issue by klassenjm** [ubsicap/usfm#7]
_Updated: April 2018_

## Updated Proposal
- Following the syntax for milestones (USFM 3.0 #33), add milestones `\ts-s` and `\ts-e` for identifying a section (chunk) of text suitable for translating at one time.

A companion USX 3.0 proposal exists at: ubsicap/usx#5

## Examples

Jude 5-8, ULB - using standalone milestones

``` text
\ts\*
\p
\v 5 Now I wish to remind you, although you know everything, that the Lord once saved a 
people out of the land of Egypt, but that afterward he destroyed those who did not believe.
\v 6 And angels who did not keep to their own principality, but left their proper dwelling 
place—God has kept them in everlasting chains in darkness for the judgment of the 
great day.
\ts\*
\v 7 It is just like Sodom and Gomorrah and the cities around them, which in a similar way 
gave themselves over to fornication and pursued unnatural desires. They were given as 
examples of those who suffer the punishment of eternal fire.
\v 8 Yet in the same way these also pollute their bodies in their dreams, and they reject 
authority, and they say evil things about the glorious ones.
```

Jude 5-8, ULB - using milestone pairs

``` text
\ts-s|sid="ts_JUD_5-6"\*
\p
\v 5 Now I wish to remind you, although you know everything, that the Lord once saved a 
people out of the land of Egypt, but that afterward he destroyed those who did not believe.
\v 6 And angels who did not keep to their own principality, but left their proper dwelling 
place—God has kept them in everlasting chains in darkness for the judgment of the 
great day.
\ts-e|eid="ts_JUD_5-6"\*
\ts-s|sid="ts_JUD_7-8"\*
\v 7 It is just like Sodom and Gomorrah and the cities around them, which in a similar way 
gave themselves over to fornication and pursued unnatural desires. They were given as 
examples of those who suffer the punishment of eternal fire.
\v 8 Yet in the same way these also pollute their bodies in their dreams, and they reject 
authority, and they say evil things about the glorious ones.
\ts-e|eid="ts_JUD_7-8"\*
```

-----

## OUTDATED Proposal
- Add a section marker `\ts` to identify a chunk of text suitable for translating at one time.
- The `\ts` marker must be on its own line.

A companion USX 3.0 proposal exists at: ubsicap/usx#5

#### Details
- `\ts` is strictly a non-publishable aid to translators. It does not indicate a true paragraph break nor a section or section heading in the published form of a text. Since it is implemented in USFM as a paragraph type, it will likely form a paragraph boundary in the text in a USFM editor like Paratext.

## Examples

Jude 5-8, ULB

``` text
\ts
\p
\v 5 Now I wish to remind you, although you know everything, that the Lord once saved a 
people out of the land of Egypt, but that afterward he destroyed those who did not believe.

\v 6 And angels who did not keep to their own principality, but left their proper dwelling 
place—God has kept them in everlasting chains in darkness for the judgment of the 
great day.

\ts
\v 7 It is just like Sodom and Gomorrah and the cities around them, which in a similar way 
gave themselves over to fornication and pursued unnatural desires. They were given as 
examples of those who suffer the punishment of eternal fire.

\v 8 Yet in the same way these also pollute their bodies in their dreams, and they reject 
authority, and they say evil things about the glorious ones.
```

**Comment by jag3773** [comment]
Wow, I didn't realize this existed when I wrote https://github.com/ubsicap/usfm/issues/22#issuecomment-260785543 !  Clearly, having `\ts` would be ideal as it is much more precise.

**Comment by jag3773** [comment]
@klassenjm We are planning to start using `\ts` in our translations soon, unless you would advise us against it.

**Comment by klassenjm** [comment]
@jag3773 Jeese -- Would it be true that translator chunks would be less than a full paragraph? If so, the implementation of this as a paragraph type will be awkward, especially in USX (ubsicap/usx#5), since it would need to either contain the verse text, or interrupt it, requiring a paragraph container to wrap the remaining text.

If chunks would be less than a paragraph, then this would seem to be better implemented as a milestone. (I'd rather not go there if chunks do not really interrupt paragraphs.).

**Comment by lrsallee** [comment]
Would this replace \s5 that we currently use as chunk breaks?

**Comment by klassenjm** [comment]
@lrsallee If the `\s5` is to mark small units to divide translation work, then yes, this is the intent of `\ts`

If you are currently using `\s5`, then it sounds like make a requirement that these chunk markers occur at paragraph boundaries would be OK (and preferred).

**Comment by jag3773** [comment]
The divisions that we currently have do interrupt paragraphs.

**Comment by klassenjm** [comment]
@jag3773 Jesse, I really don't want to propose backtracking on this. I believe you have already implemented in some measure. However, it seems that this would be much more naturally implemented as a standalone milestone, like:

```text
\ts\*
\p
\v 5 Now I wish to remind you, although you know everything, that the Lord once saved a 
people out of the land of Egypt, but that afterward he destroyed those who did not believe.
\v 6 And angels who did not keep to their own principality, but left their proper dwelling 
place—God has kept them in everlasting chains in darkness for the judgment of the 
great day.
\ts\*
\v 7 It is just like Sodom and Gomorrah and the cities around them, which in a similar way 
gave themselves over to fornication and pursued unnatural desires. They were given as 
examples of those who suffer the punishment of eternal fire.
\v 8 Yet in the same way these also pollute their bodies in their dreams, and they reject 
authority, and they say evil things about the glorious ones.
```

This is especially true for a USX view of the same data. It would involve introducing a new level of nested structure.

How problematic would a shift be right now for your team? (In terms of markup syntax only, the change is quite small.)

**Comment by jag3773** [comment]
We can make that change @klassenjm .  We have not yet done a wholesale update of the markers we are currently using, so changing to the milestone structure sounds good if that makes more sense with the rest of the spec.

**Comment by RobH123** [comment]
@klassenjm (Sorry not really sure if the correct GitHub protocol is to open a new issue rather than commenting in a closed issue?)

https://ubsicap.github.io/usfm/milestones/index.html#standalone-milestones includes this:

> Milestones do not need to occur in pairs or require the use of start -s and end -e marker suffixes. The syntax can also be used for a standalone milestone...
> 
> Currently, USFM does not formally provide any standalone milestones. This may change with future updates to USFM 3.x, as use of milestones highlights specific needs.

and yet it (and also in your previous comment in this issue) shows an example of a standalone \ts\* milestone.

Can you pls clarify the USFM3 milestone documentation by either 1/ removing the \ts\* example, or 2/ clarifying the text quoted above which says that the current standard has no ("formal", whatever that means) standalone milestones. Thanks.
