### ISSUE TITLE
Word level attributes - morphology?

### ISSUE THREAD

**Issue by DavidHaslam** [ubsicap/usfm#71]
In the absence of an example in the documentation, let's assume that this would be implemented like this:
```
\w Abraham|strong="G0011" robinson="N-PRI"\w*
```
This illustration is from **Matthew 1:2**.

This should convert to OSIS XML as follows:
```
<w lemma="strong:G0011" morph="robinson:N-PRI">Abraham</w>
```
NB. The conversion script has to 'know' that 
- **strong** becomes a **lemma** attribute
- **robinson** becomes a **morph** attribute

**Aside**: _This may not be obvious if you're just looking at the USFM syntax._

Anyway, it would be helpful to include an example of morphology in word level attributes.

### Further information (OSIS)
- For NT Greek morphology, the reference work is usually `<refSystem>Dict.Robinsons</refSystem>`.
- For Hebrew morphology, the reference work may be `<refSystem>Dict.strongMorph</refSystem>`.

Here's an example of the latter in Genesis 1:1.
```
<w lemma="strong:H0853 strong:H01254" morph="strongMorph:TH8804">created</w>
```

Aside: _It would be good if ParaTExt 8 might be enhanced to support **morphology** attributes._

**Comment by klassenjm** [comment]
@DavidHaslam In USFM 3 there is not a defined word level attribute for morphology / morph.

> Using the general syntax, attributes may be added to any character markers beyond the formally provided set for the current version of USFM. These will not be considered strictly USFM compliant, and there is no assurance that they will be supported by compliant software tools or processes. Future versions of USFM may formally provide additional attributes.
> 
> Any user defined attributes must begin with the prefix x-.

So, if you wanted to use `robinson`, it would need to be `x-robinson`.

USFM 3.1 etc. could encode an additional collection of attributes which have sufficient support. If you want to add recommendations, please feel free. It would be great to include a 1) concise recommendation and 2) some examples.

I'm going to close this for now, but feel free to reference it.
