### ISSUE TITLE
Using \rem in context anywhere in a USFM file?

### ISSUE THREAD

**Issue by DavidHaslam** [ubsicap/usfm#83]
The `\rem text` tag is specified under **Identification** with the following description:

> * Used for adding brief comments by a translator, consultant, or support person. 

Some interpret this as thereby implying that one should not use \rem in context anywhere else in a USFM file!

So for example, the following is strictly speaking an inappropriate place to have such:
```
\c 9
\cl ПCАЛЬМА 9

\s2 Падзякаваньне за вызваленьне
\rem Verse 1 is the descriptive title
\rem Acrostic title Самэх is missing. Some others may be misplaced?
\p

\v 1  Кіроўцу хору. Пасьля сьмерці Лабэна. Псальма Давідава.
```
Observe that this use of `\rem ` does not depart from how it's defined, only that its placement is not part of the **Identification** header lines before content that's to be rendered begins.

Please provide a clear statement in the documentation about this use of contextual comments using `\rem `.  _Thanks_.

**Comment by DavidHaslam** [comment]
_I still await a response_.

Please clarify by updating [#rem](http://ubsicap.github.io/usfm/identification/index.html?highlight=rem#rem)

**Comment by openenglishbible** [comment]
Paratext's Basic Check goes wrong if you have a `\rem` in the body of the USFM file, which suprised me when I came across it because I didn't expect it from the USFM documentation. 

I have found the ability to add source level remarks which don't appear in rendered output to be very useful.

**Comment by klassenjm** [comment]
@openenglishbible The current 3.0 stylesheets permit \rem under `id` and `c` - meaning that it can occur within the introduction or the scripture text. In my tests (using Paratext 9 currently) I am not finding any checking errors when adding `\rem` within the text at various location (note that `\rem` is always a new paragraph)
