### ISSUE TITLE
Newlines

### ISSUE THREAD

**Issue by jaakristioja** [ubsicap/usfm#87]
From https://ubsicap.github.io/usfm/about/syntax.html#newlines:
> USFM processors should treat the single CR (U+000D) or LF (U+000A) characters, and the sequence Carriage Return-Line Feed (CRLF), like a single LF character.

Should CR CR CR LF be treated like CR CR LF (collapsing the CR LF), like CR LF (collapsing CR LF twice) or like a single LF (collapsing CR LF three times)?

**Comment by davidg-sil** [comment]
I think the point is that it would be treated as 3*LF: (CR) (CR) (CRLF), and since:
_"USFM considers space (U+0020), tab (U+0009), and newline characters to be whitespace."_

3*LF  is probably two or three pieces of insignificant whitespace, depending if there's any reason to consider one of them significant.

**Comment by cmahte** [comment]
Whitespace is generally all reprocessed by USFM. All whitespaces  (returns,
linefeeds, tabs, spaces, no break spaces, tildes) are treated equally, but
supported and repaired.

Paratext removes all line endings and reintroduces line endings prior to
paragraph tags, chapter tags, and verse tags for internal display.   but
the Line endings prior to verse tags are almost always removed for export
to any external display or printing. There used to be a flow that if
scripture had NO paragraph tags, the returns prior to verse numbers were
left present (creating a verse per line output.)  I don't think any new
USFM work supports that, but I'm not sure.  That is, Paratext displays an
error if you introduce a verse number after a chapter number with no
paragraph tag in between.

So, to answer your question, Proper handling in USFM is that multiple
whitespace characters in sequence are treated the same as a single
whitespace character.

(and NOTE:) - I list tilde (explicit no break space character) above.
Currently, paratext internally does not treat this character as "any"
whitespace, but as a 'word' character. However, it gets more complicated on
export, but mostly it replaces any whitespace near it on export. So the
statement remains truer than it is false that it's treated in this group of
'any whitespace is treated the same'.

**Comment by jaakristioja** [comment]
> Whitespace is generally all reprocessed by USFM. All whitespaces  (returns,
linefeeds, tabs, spaces, no break spaces, tildes) are treated equally, but
supported and repaired.

What exactly do you mean by "reprocessed" (some time after parsing?), "treated equally" and "repaired"?

> Paratext removes all line endings and reintroduces line endings prior to
paragraph tags, chapter tags, and verse tags for internal display.   but
the Line endings prior to verse tags are almost always removed for export
to any external display or printing. There used to be a flow that if
scripture had NO paragraph tags, the returns prior to verse numbers were
left present (creating a verse per line output.)  I don't think any new
USFM work supports that, but I'm not sure.  That is, Paratext displays an
error if you introduce a verse number after a chapter number with no
paragraph tag in between.

I take that this paragraph about the specifics of reintroducing line endings in some later stages of processing in ParaTExt is irrelevant to parsing USFM?

> So, to answer your question, Proper handling in USFM is that multiple
whitespace characters in sequence are treated the same as a single
whitespace character.

Do I understand you correctly, that `CR CR CR` would be collapsed to `CR`, `LF LF LF` to `LF` and this stage of processing happens before collapsing the `CR LF` pairs to `LF`? Is this what is called ["whitespace normalization"](https://ubsicap.github.io/usfm/about/syntax.html#whitespace-normalization)? Are both `CR` and `LF` considered "newline" characters and hence whitespace?

And this does still not fully answer my question with respect to how a USFM lexer should handle its input. If collapsing of whitespace characters happens before converting `CR LF` to `LF`, then the input `LF CR CR CR LF CR CR CR LF` would first be collapsed to `LF CR LF CR LF` and then to `LF LF LF`. Would this then again be collapsed to `LF`?

> (and NOTE:) - I list tilde (explicit no break space character) above.
Currently, paratext internally does not treat this character as "any"
whitespace, but as a 'word' character. However, it gets more complicated on
export, but mostly it replaces any whitespace near it on export. So the
statement remains truer than it is false that it's treated in this group of
'any whitespace is treated the same'.

Since this is another detail ParaTExt specifics on USFM export, I suppose this is also not directly relevant to the parsing issue at hand? Correctly written lexers/parsers should be able to properly handle any input, including incorrect input (usually by rejecting it).

PS: All this would be much clearer with more formalization of the grammar in the USFM specification. EBNF? :smiley:

**Comment by davidg-sil** [comment]
Sorry, typing as someone who's not had anything to do with writing the spec,  just read it a few times over the years, I think it's fairly clear: New lines are white space; CR, CRLF and LF are all counted as new lines; repeated white space is not significant. Therefore, if you're parsing USFM, you can collapse multiple new lines or strange combinations of CR and LF to a single one. And sometimes you can totally ignore them. (e.g. between bits of text with no markers nearby) But don't forget EVERY newline, as there are a few places where it is considered significant.

**Comment by jaakristioja** [comment]
> New lines are white space; CR, CRLF and LF are all counted as new lines; repeated white space is not significant. Therefore, if you're parsing USFM, you can collapse multiple new lines or strange combinations of CR and LF to a single one.

In [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form) could this simply be expressed as follows?

```EBNF
newline ::= { "\r" | "\n" };
```

**Comment by cmahte** [comment]
In EBNF <https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form> could
this simply be expressed as follows?

newline ::= { "\r" | "\n" };

You could.

Except you still have to deal with the verses being separated by newlines
extraneously.  Inside USFM, the newline before the \v tag is strictly to
allow searches to report results in scripture BCV format. This is done so
that integrity tests can be performed on specific verses with known
attributes: for example: does the proper name Abraham match in all the
verses where it should occur, and is it different from the proper name
Abram? These integrity tests are possible through the clear separation of
verses. if you're converting INTO USFM, all \v tags should have newlines
before them. If you're converting from USFM, newlines should (almost
always) be removed from prior to \v tags.

(I've previously mentioned a very old form of USFM which interpreted NO
paragraph tags as verse per paragraph.... that's an exception that may
still be present in some USFM. If there is no paragraph tag between the \c
tag and the \v tag, then all \v tags should represent new paragraphs. This
was explicitly stated rule in USFM 2.2(?) or earlier. It's not in the USFM
2.6 or 3.0 manual now as far as I know. I don't know if you'll ever see
USFM that uses this or not.)

Those "[newline]+\v" tags are effectively database record boundaries, not
paragraph delimiters for output. When the USFM is transformed into print or
digital output, the tags themselves are evaluated without the newlines to
arrive at display formatting. Newlines are basically all scrubbed out, and
line endings occur only where paragraph boundaries are specified.

**Comment by jaakristioja** [comment]
> You could.

Beside this simple sentence, almost everything else in the explanations given have made the matter even less clear for me. 

Originally I was thinking about writing a parser for USFM. But right now I'm sorry, its too messy for me and I'm giving up at this point. :crying_cat_face:

**Comment by klassenjm** [comment]
@jaakristioja You might want to take a look at this project: https://github.com/Bridgeconn/usfm-grammar

**Comment by jaakristioja** [comment]
@klassenjm Thanks! That makes way more sense to me.
