### ISSUE TITLE
\pc marker in \peripheral materials

### ISSUE THREAD

**Issue by lpditto** [ubsicap/usfm#89]
Some of the members of my branch have recently had the \pc marker appear in red when used on a \periph book. Specifically in the FRT book. In the documentation the \pc marker is shown to be the proper marker, so I was wondering why the color change, and do we need to make any changes to our formatting?
![Annotation 2019-07-27 135057](https://user-images.githubusercontent.com/40044527/61989607-bf615500-b075-11e9-8336-289906b3e6b9.png)

**Comment by klassenjm** [comment]
Hi,

The rules for valid markup within scripture text is somewhat different than for peripheral books (peripherals don't have chapter markers, which invalidates many of the default checking rules defined in the standard USFM stylesheet in Paratext)

You can add a file call frtbak.sty to your project folder to provide an alternate set of rules for non-scripture books. There should be a copy of a frtbak.sty file within your \My Paratext 8 Projects folder. Copy that into your current project folder. In case you do not find that file there, here is a [link](https://www.dropbox.com/s/gou7qby5kp3znvm/frtbak.sty?dl=0) to a copy.

You can look up frtbak.sty in the Paratext help for a more thorough explanation.
