### ISSUE TITLE
Links are too light

### ISSUE THREAD

**Issue by mhosken** [ubsicap/usfm#93]
The link colour makes them unreadable on low contrast screens. Makes for very uncomfortable reading. Perhaps the link colour could become the hover colour and the hover/visited colour darker still. I think the issues is exacerbated by the small text size.

I must admit to not being a fan of reduced contrast text for documentation. Perhaps if the text were black, then there would be more colour space for links to become readable again. You can't have both reduced contrast and small text. That's just cruelty to readers.

**Comment by klassenjm** [comment]
@mhosken A modest update, Martin. I hope it's a bit better now. Slightly darker, and an underline decoration for hover. If the links became too dark, they begin to hide themselves in the text. I was not ready to make a more major update to the style or colors.
