### ISSUE TITLE
ca cp | va vp : specification allows standalone usage?  (va with no v?, etc) 

### ISSUE THREAD

**Issue by cmahte** [ubsicap/usfm#95]
In an open issue here: 

https://github.com/adyeths/u2o/issues/98

The included example Includes a canonical introduction to esther where all preface text is marked with cp and va. 

It is possible that the USFM specification should be enhanced to clarify that the cp and ca are subordinate modifiers to a c tag, and that the va and vp tags are subordinate modifiers to a v tag. That is, the ca, cp, va, vp tags should not be used without their parent tags, as happens in this example. The documentation should state this more clearly.

Second, I've previously suggested that the \c 0 be included as a way to allow for canonical introductions.  This issue is real and present, as can be seen in the example.

**Comment by klassenjm** [comment]
Hello Michael,

Thanks for pointing to this example. It appears to be a file containing "Esther Greek" (ESG) (portions of Esther found in the Greek translation of the Hebrew book of Esther). In my experience, these texts potentially ordered with chapter and verse markup in multiple different ways depending on the audience and church tradition the text is being published for, and how the text is published with or separate from the other parts of Esther. It has always been somewhat difficult to understand how the portions fit together, for me.

As USFM did emerge and grew out of some of the practices developed in the Paratext application, there was a need for markup which could identify the chapters and verses to actually display in a published text, even though Paratext expected a sequential order of chapter and verse markers. Different projects have atempted to describe the structure of ESG within this Paratext constraint using \cp and \vp. \ca and \va are normally used for showing multiple (an alternate) versififcation schemes.

You referered to a canonical introduction. I think I understand why you have described the text this way. In an English text example (Good News), the current project markup is as follows

```
\c 1
\cp A
\s Mordecai's Strange Dream
\p
\v 1-3 Mordecai, a Jew who belonged to the tribe of Benjamin, was taken into exile, 
along with King Jehoiachin of Judah...
...
\p
\v 17 But Haman son of Hammedatha, a Bougaean who was respected by the king, 
tried to cause trouble for Mordecai and his people the Jews, because Mordecai had 
been responsible for the death of the two eunuchs.
\cp 1
\s Queen Vashti Defies King Xerxes
\p
\v 18-19 \vp 1-2\vp* These things happened in the time of King Xerxes, who ruled 
127 provinces, all the way from India to Ethiopia,b from his royal throne in Susa, 
Persia's capital city.
\v 20 \vp 3\vp* In the third year of his reign, the king gave a banquet for all his 
advisers
...
```

The \cp (as a Paragraph type) appears within a sequential chapter section on its own (like `\cp 1`) -- or immediately after a `\c` (like `\cp A`).

As I mentioned, the pratice of marking up ESG is somewhat varied, and challenging. Does this alternative example help shed light on what others do and have done with this?

**Comment by cmahte** [comment]
Thank you for the example. 

It did help explain how \cp works.  it was not clear that the \cp tag isn't strictly subordinate to the \c tag (only allowed immediately after.) but this does make it less confusing, if that's possible.
