### ISSUE TITLE
Is the spacing wrong in footnote format examples?

### ISSUE THREAD

**Issue by RobH123** [ubsicap/usfm#98]
From http://ubsicap.github.io/usfm/master/about/syntax.html#endmarkers-in-footnotes-and-cross-references:

```
    \f + \fk Issac:\ft In Hebrew means "laughter"\f*
    \f + \fk Issac:\fk* \ft In Hebrew means "laughter"\ft*\f*

    \f + \fr 1.14 \fq religious festivals;\ft or \fqa seasons.\f*
    \f + \fr 1.14\fr* \fq religious festivals;\fq* or \fqa seasons.\fqa*\f*

    \f + \fr 2.4 \fk The \+nd Lord\+nd*: \ft See \+nd Lord\+nd* in Word List.\f*
    \f + \fr 2.4\fr* \fk The \+nd Lord\+nd*:\fk* \ft See \+nd Lord\+nd* in Word List.\ft*\f*
```

Should the first lines of the first two example pairs have a space before the \ft like the third one? (I'm not certain that the first two pairs will produce the same printed result?)

**Comment by klassenjm** [comment]
Hello Robert - Yes, you're correct. They should be:

```
 \f + \fk Issac: \ft In Hebrew means "laughter"\f*
```

and 

```
\f + \fr 1.14 \fq religious festivals; \ft or \fqa seasons.\f*
```

Thanks for identifying this. It will get fixed shortly.
