### ISSUE TITLE
Inquiry into missing number

### ISSUE THREAD

**Issue by joelthe1** [ubsicap/usfm#99]
Hey @klassenjm,
this is more out of curiosity rather than any functional need but is there a reason why the number `40` is missing from the list of [book codes](https://github.com/ubsicap/usfm/blob/master/docs/identification/books.rst). I missed it if the docs already say something about it. I guess I am looking for a good story :)

**Comment by klassenjm** [comment]
Hi Joel,

I checked with another colleague on this, to confirm. The general idea of how this happened is that:
Pre-USFM (1990's and earlier), there were defacto-SFM standards within different regions / agencies. There were also some file naming convention included in some of these specifications. 

In this convention `40` was used as something that was not a Biblical book between the testaments, perhaps "Introduction to the NT". When the file numbering system was created in early versions of Paratext (1996-97) we did not want to force the region with this convention to have to renumber all their files, so we skipped `40`. :-)

Jeff
